# Generated by Django 5.1.4 on 2025-01-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='resume',
            field=models.TextField(blank=True, null=True),
        ),
    ]
